spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:-localhost}:5432/postgres
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: public
        format_sql: true
  liquibase:
    parameters:
      row_amount: ${ROW_AMOUNT:-5k}
    labels:
      ${INDEXES:-include_indexes}
server:
  port: 8081