version: '3.9'

services:

  mongodb:
    container_name: mongo_container
    restart: always
    image: mongo:5.0
    ports:
      - 27017:27017

  oracle-db:
    container_name: oracle_container
    restart: always
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 1521:1521

  postgres:
    container_name: postgres_container
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
       - postgres:${PGDATA:-/data/postgres}
    ports:
      - 5432:5432


volumes:
    postgres: