#MongoDB

GET http://localhost:8082/reports/1
Accept: application/json

###
GET http://localhost:8082/reports/2
Accept: application/json

###
GET http://localhost:8082/reports/3
Accept: application/json

###

GET http://localhost:8082/reports/4
Accept: application/json

###

GET http://localhost:8082/reports/5
Accept: application/json

###

GET http://localhost:8082/reports/6
Accept: application/json

###

GET http://localhost:8082/reports/7
Accept: application/json

###
