version: '3.9'

services:

  postgres-20k:
    container_name: postgres-20k
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}

  java-postgres-20k:
    container_name: java-postgres-20k
    image: ztbd-sql
    environment:
      PROFILE: "postgres"
      ROW_AMOUNT: "20k"
      INDEXES: "no"
      POSTGRES_URL: "postgres-20k"
    depends_on:
      - postgres-20k
    ports:
      - 8007:8081

  oracle-20k:
    container_name: oracle-20k
    restart: always
    image: oracleinanutshell/oracle-xe-11g:latest

  java-oracle-20k:
    container_name: java-oracle-20k
    image: ztbd-sql
    environment:
      PROFILE: "oracle"
      ROW_AMOUNT: "20k"
      INDEXES: "no"
      ORACLE_URL: "oracle-20k"
      TZ: "GMT"
    depends_on:
      - oracle-20k
    ports:
      - 8008:8080

  mongo-20k:
    container_name: mongo-20k
    restart: always
    image: mongo:5.0

  java-mongo-20k:
    container_name: java-mongo-20k
    image: ztbd-nosql
    environment:
      MONGO_URL: "mongo-20k"
    depends_on:
      - mongo-20k
    ports:
      - 8009:8082
    command:
      - "--import=data/20k/podmioty.json.log"
      - "--collection=podmiot"
      - "--import=data/20k/przesylki.json.log"
      - "--collection=przesylka"
      - "--import=data/20k/zlecenia.json.log"
      - "--collection=zlecenie"