version: '3.9'

services:

  postgres-40k:
    container_name: postgres-40k
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}

  java-postgres-40k:
    container_name: java-postgres-40k
    image: ztbd-sql
    environment:
      PROFILE: "postgres"
      ROW_AMOUNT: "40k"
      INDEXES: "no"
      POSTGRES_URL: "postgres-40k"
    depends_on:
      - postgres-40k
    ports:
      - 8013:8081

  oracle-40k:
    container_name: oracle-40k
    restart: always
    image: oracleinanutshell/oracle-xe-11g:latest

  java-oracle-40k:
    container_name: java-oracle-40k
    image: ztbd-sql
    environment:
      PROFILE: "oracle"
      ROW_AMOUNT: "40k"
      INDEXES: "no"
      ORACLE_URL: "oracle-40k"
      TZ: "GMT"
    depends_on:
      - oracle-40k
    ports:
      - 8014:8080

  mongo-40k:
    container_name: mongo-40k
    restart: always
    image: mongo:5.0

  java-mongo-40k:
    container_name: java-mongo-40k
    image: ztbd-nosql
    environment:
      MONGO_URL: "mongo-40k"
    depends_on:
      - mongo-40k
    ports:
      - 8015:8082
    command:
      - "--import=data/40k/podmioty.json.log"
      - "--collection=podmiot"
      - "--import=data/40k/przesylki.json.log"
      - "--collection=przesylka"
      - "--import=data/40k/zlecenia.json.log"
      - "--collection=zlecenie"