spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ztbd
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
server:
  port: 8081